// Generated by https://quicktype.io

export interface RespuestaLogin {
    success:       boolean;
    expires_at:    string;
    request_token: string;
}


// Generated by https://quicktype.io

export interface RespuestaSesionID {
    success:    boolean;
    session_id: string;
}

